name: MEMAUDIT8

on:
 push:
  branches: [ master ]

# trigger workflow on file change
#on:
# push:
#  paths:
#   - 'version.txt'

# if: ${{ false }}

jobs:

# linux ----------------------------------------------------------------
 jelinux:
  name: JE (Linux)
  runs-on: ubuntu-24.04
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Linux)
     run: |
      script/install-lnx.sh
      sudo mkdir -p /usr/lib/x86_64-linux-gnu
      sudo mkdir -p /usr/lib/i386-linux-gnu
      sudo cp openmp/obj/linux/x86_64/libomp.so.5 /usr/lib/x86_64-linux-gnu/libomp.so.5
      sudo cp openmp/obj/linux/i386/libomp.so.5 /usr/lib/i386-linux-gnu/libomp.so.5

   - name: Build JE (Linux)
     env:
      CC: clang
      USE_SLEEF: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh linux || exit 1

   - name: Test JE (Linux)
     env:
      _MEMAUDIT: 8
     run: |
      script/testga.sh linux || exit 1

# macOS ----------------------------------------------------------------
 jemacos:
  name: JE (macOS)
  runs-on: macos-15-intel
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (macOS)
     run: |
      bash script/install-mac.sh

   - name: Build JE (macOS)
     env:
      CC: clang
      USE_SLEEF: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh darwin || exit 1

   - name: Test JE (macOS)
     env:
      _MEMAUDIT: 8
     run: |
      script/testga.sh darwin || exit 1

# macOS arm64 ----------------------------------------------------------
 jemacosarm:
  name: JE (macOS arm64)
  runs-on: macos-15
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (macOS arm64)
     run: |
      bash script/install-mac.sh

   - name: Build JE (macOS arm64)
     env:
      CC: clang
      USE_SLEEF: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh darwin || exit 1

   - name: Test JE (macOS arm64)
     env:
      _MEMAUDIT: 8
     run: |
      script/testga.sh darwin || exit 1

# rpi64arm -------------------------------------------------------------
 jerpi64arm:
  name: JE (Linux arm64)
  runs-on: ubuntu-24.04-arm
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Linux arm64)
     run: |
      script/install-rpi.sh

   - name: Build JE (Linux arm64)
     env:
      CC: clang
      USE_SLEEF: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh raspberry arm64 || exit 1

   - name: Test JE (Linux arm64)
     env:
      _MEMAUDIT: 8
     run: |
      script/testga.sh raspberry arm64 || exit 1

# rpi32arm -------------------------------------------------------------
 jerpi32arm:
  name: JE (Linux arm32)
  runs-on: ubuntu-24.04-arm
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Linux arm32)
     run: |
      script/install-rpi.sh

   - name: Build JE (Linux arm32)
     env:
      CC: arm-linux-gnueabihf-gcc
      USE_SLEEF: 1
      USE_SLEEFQUAD: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh raspberry armv6l || exit 1

   - name: Test JE (Linux arm32)
     env:
      _MEMAUDIT: 8
     run: |
      script/testga.sh raspberry armv6l || exit 1

# freebsd --------------------------------------------------------------
 jefreebsd2:
  name: JE (FreeBSD cross-platform-actions)
#  if: ${{ false }}
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Build, Test JE (FreeBSD)
     uses: cross-platform-actions/action@v0.32.0
     with:
      operating_system: freebsd
      architecture: x86-64
      version: '15.0'
      shell: bash

      run: |
       rm -f jobdone
       export IGNORE_OSVERSION=yes
       sudo pkg upgrade -y
       sudo rdate time.cloudflare.com || true
       sudo pkg search openblas 1>&2
       sudo pkg install -y curl zip gmake nasm pcre2 openblas
       sudo find / -type f -name 'liblapack.so*' 1>&2
       sudo find / -type f -name 'libopenblas.so*' 1>&2
       /sbin/ldconfig -r
       ls -al ~/
       ls -al ~/.ssh
       sudo echo "Host *" >>~/.ssh/config || true
       sudo echo " ServerAliveInterval 20" >>~/.ssh/config || true
       sudo echo " ServerAliveCountMax 2000000" >>~/.ssh/config || true
       echo "client ssh config"
       sudo cat ~/.ssh/config || true
       export CC=clang
       export USE_SLEEF=1
       export USE_OPENMP=0
       export _MEMAUDIT=32
       script/buildga.sh freebsd || exit 1
       script/testga.sh freebsd || exit 1
       touch jobdone

   - name: Check Status (FreeBSD)
     run: |
      test -f jobdone || exit 1

# freebsdarm64 ---------------------------------------------------------------
 jefreebsdarm64:
  name: JE (FreeBSD arm64)
#  if: ${{ false }}
#  runs-on: ubuntu-24.04-arm
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Build, Test JE (FreeBSD arm64)
     uses: cross-platform-actions/action@v0.32.0
     with:
      operating_system: freebsd
      architecture: arm64
      version: '15.0'
      shell: bash

      run: |
       rm -f jobdone
       export IGNORE_OSVERSION=yes
       sudo pkg upgrade -y
       sudo rdate time.cloudflare.com || true
       sudo pkg search openblas 1>&2
       sudo pkg install -y curl zip gmake nasm pcre2 openblas
       sudo find / -type f -name 'liblapack.so*' 1>&2
       sudo find / -type f -name 'libopenblas.so*' 1>&2
       /sbin/ldconfig -r
       ls -al ~/
       ls -al ~/.ssh
       sudo echo "Host *" >>~/.ssh/config || true
       sudo echo " ServerAliveInterval 20" >>~/.ssh/config || true
       sudo echo " ServerAliveCountMax 2000000" >>~/.ssh/config || true
       echo "client ssh config"
       sudo cat ~/.ssh/config || true
       export CC=clang
       export USE_SLEEF=1
       export USE_OPENMP=0
       export _MEMAUDIT=32
       script/buildga.sh freebsd || exit 1
       script/testga.sh freebsd || exit 1
       touch jobdone

   - name: Check Status (FreeBSD arm64)
     run: |
      test -f jobdone || exit 1

# wasm -----------------------------------------------------------------
 jewasm:
  name: JE (wasm)
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (wasm)
     uses: mymindstorm/setup-emsdk@v14

   - name: Build, Test JE (wasm)
     env:
      CC: emcc
      USE_SLEEF: 1
      USE_OPENMP: 0
      _MEMAUDIT: 8
     run: |
      script/buildga.sh wasm || exit 1
      script/testga.sh wasm || exit 1

# windows --------------------------------------------------------------
 jewin:
  name: JE (Windows)
  runs-on: windows-2022
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Windows)
     uses: ilammy/msvc-dev-cmd@v1
     with:
      arch: amd64

   - name: Build JE (Windows)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\buildga.cmd x64

   - name: Test JE (Windows)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\testga.cmd x64

# windows 32bit --------------------------------------------------------
 jewin32:
  name: JE (Windows 32)
  runs-on: windows-2022
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Windows 32)
     uses: ilammy/msvc-dev-cmd@v1
     with:
      arch: x86

   - name: Build JE (Windows 32)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\buildga.cmd x86

   - name: Test JE (Windows 32)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\testga.cmd x86


# windows arm64 --------------------------------------------------------
 jewinarm64:
  name: JE (Windows arm64)
  runs-on: windows-11-arm
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Setup Environment (Windows arm64)
     uses: ilammy/msvc-dev-cmd@v1
     with:
      arch: amd64_arm64

   - name: Build JE (Windows arm64)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\buildga.cmd arm64

   - name: Test JE (Windows arm64)
     shell: cmd
     env:
      _MEMAUDIT: 8
     run: |
      script\testga.cmd arm64

